### ISSUE TITLE
Server crashes when editing routes.py

### ISSUE THREAD

**Issue by testautomation** [nathanwright1242/flask_livereload_example#1]
When I apply changes to [routes.py] the server crashes with the error below.
For example I added another route
```python
@app.route('/foo')
def foo():
    return "FOO!"
```

[routes.py]: https://github.com/nathanwright1242/flask_livereload_example/blob/master/app/routes.py

```
...
'/home/wlad/projects/venv/lib/python3.7/site-packages/tornado/platform/asyncio.py':
 1546356710.0})
    Traceback (most recent call last):
      File "/home/wlad/projects/venv/lib/python3.7/site-packages/tornado/ioloop.py", line 907, in _run
        return self.callback()
      File "/home/wlad/projects/venv/lib/python3.7/site-packages/tornado/autoreload.py", line 188, in _re
load_on_update
        _check_file(modify_times, path)
      File "/home/wlad/projects/venv/lib/python3.7/site-packages/tornado/autoreload.py", line 203, in _ch
eck_file
        _reload()
      File "/home/wlad/projects/venv/lib/python3.7/site-packages/tornado/autoreload.py", line 210, in _re
load
        fn()

      File "/home/wlad/projects/venv/lib/python3.7/site-packages/livereload/server.py", line 315, in <lam
bda>
        add_reload_hook(lambda: IOLoop.instance().close(all_fds=True))
      File "/home/wlad/projects/venv/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 89, i
n close
        self.asyncio_loop.close()
      File "/usr/lib/python3.7/asyncio/unix_events.py", line 55, in close
        super().close()
      File "/usr/lib/python3.7/asyncio/selector_events.py", line 83, in close
        raise RuntimeError("Cannot close a running event loop")
    RuntimeError: Cannot close a running event loop
[I 191117 23:12:58 handlers:95] Reload 1 waiters: /home/wlad/projects/flask-livereload/app/routes.py
[W 191117 23:12:58 iostream:975] Write error on <socket.socket [closed] fd=-1, family=AddressFamily.AF_IN
ET, type=SocketKind.SOCK_STREAM, proto=6>: [Errno 9] Bad file descriptor
Task exception was never retrieved
future: <Task finished coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at /home/
wlad/projects/venv/lib/python3.7/site-packages/tornado/websocket.py:1102> exception=WebSocketClosedError(
)>
Traceback (most recent call last):
  File "/home/wlad/projects/venv/lib/python3.7/site-packages/tornado/websocket.py", line 1104, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wlad/projects/venv/lib/python3.7/site-packages/tornado/websocket.py", line 1106, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
```

**Comment by frozenpandaman** [comment]
FYI, for anyone who may encounter this in the future, I fixed by using livereload v2.5.1 instead of 2.6.3.

**Comment by frozenpandaman** [comment]
FYI, for anyone who may encounter this in the future, I was able to fix this by using livereload v2.5.1 instead of 2.6.3.

**Comment by SmartManoj** [comment]
Did you use tornado?

**Comment by frozenpandaman** [comment]
LiveReload uses Tornado.

**Comment by SmartManoj** [comment]
@frozenpandaman asked @ghost as tornado is in the stacktrace

**Comment by SmartManoj** [comment]
@frozenpandaman v2.5.1 browser does not reload when there is a change in strings?
Edit: works if The HTML files are valid.

**Comment by frozenpandaman** [comment]
@SmartManoj ghost is GitHub's name for a deleted user. ;)

**Comment by alexzanderr** [comment]
with 2.5.1 the server its not raising errors anymore, but when writing some changes to a file, it doesnt reload the page automatically. (sometimes it does, most of the times it `doesnt`)

**Comment by alexzanderr** [comment]
my config is good and everything is fine.
on what conditions does `livereload` reloads the browser page?

**Comment by frozenpandaman** [comment]
> FYI, for anyone who may encounter this in the future, I was able to fix this by using livereload v2.5.1 instead of 2.6.3.

Oh hey, thanks past me for helping me solve this again over two years later!
